// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"helloworld/internal/biz"
	"helloworld/internal/conf"
	"helloworld/internal/data"
	"helloworld/internal/data/base"
	"helloworld/internal/dep"
	"helloworld/internal/server"
	"helloworld/internal/service"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger *slog.Logger) (*kratos.App, func(), error) {
	manager, err := server.NewTokenManager(auth)
	if err != nil {
		return nil, nil, err
	}
	enforcer, err := dep.NewCasbinEnforcer()
	if err != nil {
		return nil, nil, err
	}
	middleware := server.NewSecurityMiddleware(manager, enforcer)
	db, cleanup, err := dep.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := dep.NewRedis(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseData, err := base.NewData(db, client, enforcer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	todoRepo := data.NewTodoRepo(baseData, logger)
	todoUsecase := biz.NewTodoUsecase(todoRepo, logger)
	todoService := service.NewTodoService(todoUsecase)
	grpcServer := server.NewGRPCServer(confServer, middleware, logger, todoService)
	httpServer := server.NewHTTPServer(confServer, middleware, logger, todoService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
