// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v3/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 未知错误。
func IsTodoUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TODO_UNSPECIFIED.String() && e.Code == 500
}

// 未知错误。
func ErrorTodoUnspecified(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_TODO_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

// 待办事项不存在。
func IsTodoNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TODO_NOT_FOUND.String() && e.Code == 404
}

// 待办事项不存在。
func ErrorTodoNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_TODO_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 待办事项请求参数非法。
func IsTodoInvalidArgument(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TODO_INVALID_ARGUMENT.String() && e.Code == 400
}

// 待办事项请求参数非法。
func ErrorTodoInvalidArgument(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_TODO_INVALID_ARGUMENT.String(), fmt.Sprintf(format, args...))
}
