server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: ""
    source: ""
    auto_migrate: false
  redis:
    addr: ""
    password: ""
    db: 0
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  private_key_path: ""
  access_token_ttl: 2h
  refresh_token_ttl: 168h
log:
  level: info
  filepath: ""
  rotate:
    max_size: 1024
    max_backups: 5
    max_age: 7
    compress: true
job:
  enabled: false
  queue: default
  worker_concurrency: 4
  task_timeout: 30m
  shutdown_timeout: 15s
