// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CasbinRuleColumns holds the columns for the "casbin_rule" table.
	CasbinRuleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 26},
		{Name: "version", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "ptype", Type: field.TypeString, Default: ""},
		{Name: "v0", Type: field.TypeString, Default: ""},
		{Name: "v1", Type: field.TypeString, Default: ""},
		{Name: "v2", Type: field.TypeString, Default: ""},
		{Name: "v3", Type: field.TypeString, Default: ""},
		{Name: "v4", Type: field.TypeString, Default: ""},
		{Name: "v5", Type: field.TypeString, Default: ""},
	}
	// CasbinRuleTable holds the schema information for the "casbin_rule" table.
	CasbinRuleTable = &schema.Table{
		Name:       "casbin_rule",
		Columns:    CasbinRuleColumns,
		PrimaryKey: []*schema.Column{CasbinRuleColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CasbinRuleTable,
	}
)

func init() {
	CasbinRuleTable.Annotation = &entsql.Annotation{
		Table: "casbin_rule",
	}
}
