// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/QZAiXH/kratos-layout/internal/biz"
	"github.com/QZAiXH/kratos-layout/internal/conf"
	"github.com/QZAiXH/kratos-layout/internal/data"
	"github.com/QZAiXH/kratos-layout/internal/data/base"
	"github.com/QZAiXH/kratos-layout/internal/dep"
	"github.com/QZAiXH/kratos-layout/internal/job"
	"github.com/QZAiXH/kratos-layout/internal/server"
	"github.com/QZAiXH/kratos-layout/internal/service"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, confJob *conf.Job, logger *slog.Logger) (*kratos.App, func(), error) {
	config := job.NewConfig(confJob)
	client, cleanup, err := dep.NewRedis(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	redisConnOpt := dep.NewAsynqRedisConnOpt(client)
	runtime := job.NewRuntime(config, redisConnOpt, logger)
	manager, err := server.NewTokenManager(auth)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	enforcer, err := dep.NewCasbinEnforcer()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	middleware := server.NewSecurityMiddleware(manager, enforcer)
	entClient, cleanup2, err := dep.NewDB(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseData, err := base.NewData(entClient, client, enforcer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	todoRepo := data.NewTodoRepo(baseData)
	todoUsecase := biz.NewTodoUsecase(todoRepo)
	todoService := service.NewTodoService(todoUsecase)
	grpcServer := server.NewGRPCServer(confServer, middleware, logger, todoService)
	httpServer := server.NewHTTPServer(confServer, middleware, logger, todoService)
	app := newApp(logger, runtime, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
