// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	todo2 "github.com/QZAiXH/kratos-layout/internal/biz/todo"
	"github.com/QZAiXH/kratos-layout/internal/conf"
	"github.com/QZAiXH/kratos-layout/internal/data/base"
	"github.com/QZAiXH/kratos-layout/internal/data/todo"
	"github.com/QZAiXH/kratos-layout/internal/dep"
	"github.com/QZAiXH/kratos-layout/internal/job"
	"github.com/QZAiXH/kratos-layout/internal/server"
	todo3 "github.com/QZAiXH/kratos-layout/internal/service/todo"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp 通过 Wire 初始化 Kratos 应用依赖图。
func wireApp(confServer *conf.Server, data *conf.Data, auth *conf.Auth, confJob *conf.Job, logger *slog.Logger) (*kratos.App, func(), error) {
	config := job.NewConfig(confJob)
	client, cleanup, err := dep.NewRedis(data, logger)
	if err != nil {
		return nil, nil, err
	}
	redisConnOpt := dep.NewAsynqRedisConnOpt(client)
	runtime := job.NewRuntime(config, redisConnOpt, logger)
	manager, err := server.NewTokenManager(auth)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	enforcer, err := dep.NewCasbinEnforcer()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	middleware := server.NewSecurityMiddleware(manager, enforcer)
	database, cleanup2, err := dep.NewDB(data, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseData, err := base.NewData(database, client, enforcer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	repo := todo.NewRepo(baseData)
	useCase := todo2.NewUseCase(repo)
	service := todo3.NewService(useCase)
	grpcServer := server.NewGRPCServer(confServer, middleware, logger, service)
	httpServer := server.NewHTTPServer(confServer, middleware, logger, service)
	app := newApp(logger, runtime, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
